# Generated by Django 5.0.2 on 2024-02-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_book_readers"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="is_super_active",
            field=models.BooleanField(default=True),
        ),
    ]
