# Generated by Django 5.0.2 on 2024-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_question_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="readers",
            field=models.IntegerField(default=0),
        ),
    ]
